### ISSUE TITLE
咋没人的呢，好孤独哦~~

### ISSUE THREAD

**Issue by jadestone-web3** [jadeStoneStonger/SSO#2]

**Comment by jadestone-web3** [comment]
close

**Comment by wy7832733** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jadeStone"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 中午11:12
收件人:&nbsp;"jadeStoneStonger/SSO"<SSO@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jadeStoneStonger/SSO] 咋没人的呢，好孤独哦~~ (#2)





 
Closed #2.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

???业哥又在钻研什么技术？

**Comment by jadestone-web3** [comment]
刚把spring1，2，3的源码都fork了一下，准备2个月看完spring。公司在用docker,k8s也在学习

**Comment by wy7832733** [comment]
业哥步伐太快，我根本跟不上啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jadeStone"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 中午11:26
收件人: "jadeStoneStonger/SSO"<SSO@noreply.github.com&gt;; 
抄送: "YORK"<1006311488@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jadeStoneStonger/SSO] 咋没人的呢，好孤独哦~~ (#2)





 
刚把spring1，2，3的源码都fork了一下，准备2个月看完spring。公司在用docker,k8s也在学习

**Comment by jadestone-web3** [comment]
我已经落伍两年了。。

**Comment by wy7832733** [comment]
这个两年是怎么算出来的？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jadeStone"<notifications@github.com&gt;; 
发送时间: 2020年5月9日(星期六) 中午11:39
收件人: "jadeStoneStonger/SSO"<SSO@noreply.github.com&gt;; 
抄送: "YORK"<1006311488@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jadeStoneStonger/SSO] 咋没人的呢，好孤独哦~~ (#2)





 
我已经落伍两年了。。

**Comment by jadestone-web3** [comment]
毕业四年，每天玩一半，可不就是两年了。。。哈哈
